services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "${PORT}:${PORT}" # http(s)
      - 24678:24678 # HMR
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ${CERTS_VOLUME_DIR}:/certs:ro
      - ${DB_VOLUME_DIR}:/db:rw
      - ${LOGS_VOLUME_DIR}:/logs:rw
    develop:
      watch:
        # sync scripts so the container has the latest versions
        - path: ./scripts
          action: sync
          target: /app/scripts
        # sync client-side files (let HMR take care of them)
        - path: ./src
          action: sync
          target: /app/src
        - path: ./public
          action: sync
          target: /app/public
        - path: ./dist
          action: sync
          target: /app/dist
        # rebuild if server files change
        - path: ./main.ts
          action: rebuild
          target: .
        - path: ./server
          action: rebuild
          target: .
        - path: ./CHANGELOG.md
          action: rebuild
          target: .
        # specifically DO NOT rebuild if the db schema changes
        # - path: ./prisma
        #   action: nothing
        #   target: .
        # rebuild if deps change
        - path: ./package.json
          action: rebuild
          target: .
        - path: ./package-lock.json
          action: rebuild
          target: .
        # rebuild if any vite or TS configs change
        - path: ./postcss.config.js
          action: rebuild
          target: .
        - path: ./tailwind.config.js
          action: rebuild
          target: .
        - path: ./vite.config.ts
          action: rebuild
          target: .
        - path: ./tsconfig.*
          action: rebuild
          target: .

  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: -E UTF8
    volumes:
      - ./scripts/healthchecks:/healthchecks
      - ${DB_VOLUME_DIR}/postgres:/var/lib/postgresql/data:rw
      - ${DB_VOLUME_DIR}:/data:rw
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
