# This should always be used alongside docker-compose.base.yaml:
# docker compose -f docker-compose.base.yaml -f docker-compose.production.yaml ...

services:
  app:
    build:
      target: prod
    restart: unless-stopped
