services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: -E UTF8
    volumes:
      - ./scripts/healthchecks:/healthchecks
      - ${DB_VOLUME_DIR}/postgres:/var/lib/postgresql/data:rw
      - ${DB_VOLUME_DIR}:/data:rw
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
