services:
  app:
    build:
      context: .
      # build to the dev stage
      target: dev
      args:
        # This needs to be set for prisma commands
        # TODO: This will change when we change to Postgres
        DB_APP_DB_URL: "file:/db/trackbear.db"
    ports:
      - "${PORT}:${PORT}" # http(s)
    env_file:
      - ./.env
    volumes:
      - ${CERTS_VOLUME_DIR}:/certs:ro
      - ${DB_VOLUME_DIR}:/db:rw
      - ${LOGS_VOLUME_DIR}:/logs:rw
