services:
  app:
    image: dispatchrabbi/trackbear:latest
    ports:
      - "${PORT}:${PORT}" # http(s)
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ${CERTS_VOLUME_DIR}:/certs:ro
      - ${DB_VOLUME_DIR}:/db:rw
      - ${LOGS_VOLUME_DIR}:/logs:rw
