# This should always be used alongside docker-compose.base.yaml:
# docker compose -f docker-compose.base.yaml -f docker-compose.development.yaml ...

services:
  app:
    ports:
      - "24678:24678"     # add ws for HMR
    # TODO: migrate from sqlite to postgres
    # depends_on:
    #   db:
    #     condition: service_healthy
    develop:
      watch:
        # sync scripts so the container has the latest versions
        - path: ./scripts
          action: sync
          target: /app/scripts
        # sync client-side files (let HMR take care of them)
        - path: ./src
          action: sync
          target: /app/src
        - path: ./public
          action: sync
          target: /app/public
        - path: ./dist
          action: sync
          target: /app/dist
        # rebuild if server files change
        - path: ./main.ts
          action: rebuild
          target: .
        - path: ./server
          action: rebuild
          target: .
        - path: ./CHANGELOG.md
          action: rebuild
          target: .
        # specifically DO NOT rebuild if the db schema changes
        # - path: ./prisma
        #   action: nothing
        #   target: .
        # rebuild if deps change
        - path: ./package.json
          action: rebuild
          target: .
        - path: ./package-lock.json
          action: rebuild
          target: .
        # rebuild if any vite or TS configs change
        - path: ./postcss.config.js
          action: rebuild
          target: .
        - path: ./tailwind.config.js
          action: rebuild
          target: .
        - path: ./vite.config.ts
          action: rebuild
          target: .
        - path: ./tsconfig.*
          action: rebuild
          target: .

  # db:
  #   image: postgres:alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./healthchecks:/healthchecks
  #   healthcheck:
  #     test: /healthchecks/postgres-healthcheck
  #     interval: "5s"
