receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: trackbear-jaeger-all-in-one-1:4317
    tls:
      insecure: true
      insecure_skip_verify: true

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    # traces/debug:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]