output-dir: "{cwd}/help-docs/public/openapi"
emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
    file-type: "json"
    openapi-versions:
      - 3.1.0
