name: Build and push docker image from tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get metadata for images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dispatchrabbi/trackbear
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          image: ghcr.io/dispatchrabbi/trackbear
          registry: ghcr.io
          githubOrg: override-org # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
