name: Publish help release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release-help:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build help docs
        run: |
          npm run compile:api
          npm run compile:help
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: trackbear-help ${{ github.ref_name }}
          files: help-docs/.vitepress/dist/**/*.*
          fail_on_unmatched_files: true
          make_latest: false
